# Generated by Django 5.0.7 on 2024-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('eventDate', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=255)),
                ('eventImage', models.ImageField(upload_to='eventImages')),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('datePosted', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('authorImage', models.ImageField(upload_to='newsAuthorImage')),
                ('newsImage', models.ImageField(upload_to='newsImages')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
